// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "error.hpp"

blitz::error::~error() {}

blitz::error::error(std::filesystem::path file, std::pair<uint64_t, uint64_t> base, std::pair<uint64_t, uint64_t> at, std::string reason) : std::runtime_error(reason)
{
	_file = file;
	_base = base;
	_at   = at;
}

std::filesystem::path const& blitz::error::file() const
{
	return _file;
}

std::pair<uint64_t, uint64_t> const& blitz::error::base() const
{
	return _base;
}

std::pair<uint64_t, uint64_t> const& blitz::error::at() const
{
	return _at;
}
