// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#pragma once
#include <cinttypes>
#include <filesystem>
#include <stdexcept>
#include <string>
#include <utility>

namespace blitz {
	class error : public std::runtime_error {
		std::filesystem::path         _file;
		std::pair<uint64_t, uint64_t> _base;
		std::pair<uint64_t, uint64_t> _at;

		public:
		~error();
		error(std::filesystem::path file, std::pair<uint64_t, uint64_t> base, std::pair<uint64_t, uint64_t> at, std::string reason);

		std::filesystem::path const& file() const;

		std::pair<uint64_t, uint64_t> const& base() const;

		std::pair<uint64_t, uint64_t> const& at() const;
	};
} // namespace blitz
