/// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#pragma once
#include <filesystem>
#include <fstream>
#include <inttypes.h>
#include <iostream>
#include <istream>
#include <memory>
#include <string>
#include <utility>

// ToDo:
// - Figure out a way to let the lexer output line and character information?

namespace blitz {
	struct token {
		uint64_t    line;
		uint64_t    character;

		std::string text;
		enum class variant : uint64_t {
			UNKNOWN, // We have absolutely no fucking clue.
			CONTROL, // All kinds of control signals, like NewLine, EndOfFile, ...
			SYMBOL, // All kinds of symbols.
			TEXT, // HelloWorld
			NUMBER, // 1, 1%
			DECIMAL, // 1.0, 1#
			STRING, // "HelloWorld"
			COMMENT, // ; Whatever
		} type;
	};

	class lexer {
		std::filesystem::path _file;
		std::ifstream         _stream;

		// Current location in the file.
		uint64_t _line;
		uint64_t _character;

		blitz::token _current;
		blitz::token _override;

		public:
		~lexer();
		lexer(std::filesystem::path file);

		/** Retrieve the current token information.
		 */
		blitz::token current();

		/** Retrieve the next token in the given stream.
		 *
		 * This will replace the current token.
		 */
		blitz::token next();
	};
} // namespace blitz
