// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2025 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "types.hpp"
#include <algorithm>
#include <cctype>

const std::pair<const char*, blitz::types::type> _map_to[] = {
	{ "byte", blitz::types::type::INT8 },       //
	{ "int8", blitz::types::type::INT8 },       //
	{ "ubyte", blitz::types::type::UINT8 },     //
	{ "uint8", blitz::types::type::UINT8 },     //
	{ "short", blitz::types::type::INT16 },     //
	{ "int16", blitz::types::type::INT16 },     //
	{ "ushort", blitz::types::type::UINT16 },   //
	{ "uint16", blitz::types::type::UINT16 },   //
	{ "int", blitz::types::type::INT32 },       //
	{ "int32", blitz::types::type::INT32 },     //
	{ "uint", blitz::types::type::UINT32 },     //
	{ "uint32", blitz::types::type::UINT32 },   //
	{ "long ", blitz::types::type::INT64 },     //
	{ "int64", blitz::types::type::INT64 },     //
	{ "ulong", blitz::types::type::UINT64 },    //
	{ "uint64", blitz::types::type::UINT64 },   //
	{ "half", blitz::types::type::FLOAT16 },    //
	{ "float16", blitz::types::type::FLOAT16 }, //
	{ "real16", blitz::types::type::FLOAT16 },  //
	{ "single", blitz::types::type::FLOAT32 },  //
	{ "float", blitz::types::type::FLOAT32 },   //
	{ "float32", blitz::types::type::FLOAT32 }, //
	{ "real", blitz::types::type::FLOAT32 },    //
	{ "real32", blitz::types::type::FLOAT32 },  //
	{ "double", blitz::types::type::DOUBLE },   //
	{ "float64", blitz::types::type::DOUBLE },  //
	{ "real64", blitz::types::type::DOUBLE },   //
	{ "string", blitz::types::type::STRING },   //
};

std::string blitz::types::to_string(blitz::types::type type)
{
	if (type == type::STRUCT) {
		return "struct";
	}

	for (auto kv : _map_to) {
		if (type == kv.second) {
			return kv.first;
		}
	}

	return "Unknown";
}

blitz::types::type blitz::types::from_string(std::string text)
{
	std::transform(text.cbegin(), text.cend(), text.begin(), [](char from) {
		if (from & 0b10000000) { // Exclude Unicode
			return from;
		}
		return (char)std::tolower(from);
	});

	for (auto kv : _map_to) {
		if (text == kv.first) {
			return kv.second;
		}
	}

	return blitz::types::type::UNKNOWN;
}
