
// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2025 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#pragma once
#include <cinttypes>
#include <string>

namespace blitz {
	namespace types {
		enum class type : uint8_t {
			UNKNOWN,
			// 8-bit Integers
			INT8,
			BYTE = INT8,
			UINT8,
			UBYTE = UINT8,
			// 16-bit Integers
			INT16,
			SHORT = INT16,
			UINT16,
			USHORT = UINT16,
			// 32-bit Integers
			INT32,
			INT = INT32,
			UINT32,
			UINT = UINT32,
			// 64-bit Integers
			INT64,
			LONG = INT64,
			UINT64,
			ULONG = UINT64,
			// 16-bit Float
			FLOAT16,
			HALF = FLOAT16,
			// 32-bit Float
			FLOAT32,
			FLOAT = FLOAT32,
			SINGLE = FLOAT32,
			// 64-bit Float
			FLOAT64,
			DOUBLE = FLOAT64,
			// UTF-8 String
			STRING,
			// User-defined Struct
			STRUCT,
		};

		std::string to_string(blitz::types::type type);
		blitz::types::type from_string(std::string text);
	};
} // namespace blitz
