// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2025 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

namespace blitz::utility {
	bool is_symbol(int code);

	bool is_white_space(int code);

	bool is_digit(int code);

	bool is_alpha(int code);
} // namespace blitz::utility
