; AUTOGENERATED COPYRIGHT HEADER START
; Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
; AUTOGENERATED COPYRIGHT HEADER END
Graphics 800,600,32,2
SetBuffer BackBuffer()

Local value% = 1
If value == 1 Then
	Print "Hello World"
EndIf