; AUTOGENERATED COPYRIGHT HEADER START
; Copyright (C) 2025 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
; AUTOGENERATED COPYRIGHT HEADER END
Variable
Variable%
Variable%%
Variable#
Variable##
Variable$
Variable$$
Variable:Int
Variable:Float
Variable:String
Variable:Int8
Variable:Int16
Variable:Int32
Variable:Int64
Variable:UInt8
Variable:UInt16
Variable:UInt32
Variable:UInt64
Variable:Half
Variable:Single
Variable:Double
Variable:Real
Variable:Float16
Variable:Float32
Variable:Float64
Variable:Real16
Variable:Real32
Variable:Real64
0
0x
0b
0b100
0b100u
0x100
0x100u
255
255u
65535
65535u
"Level Up"
"Hello World"
True
False
Null
Local myVar%, myVar2#
Global gVar$, gVar15:Int32
Global gHelloWorld$ = "Hello World", localVarThatIsntLocal
