/// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "arithmetic.hpp"

blitz::ast::arithmetic_expression::arithmetic_expression(expression_operator op, std::unique_ptr<expression> left, std::unique_ptr<expression> right)
	: m_operator(op), m_left(std::move(left)), m_right(std::move(right)) {}

blitz::ast::arithmetic_expression::~arithmetic_expression() {}
