/// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "function.hpp"

blitz::ast::ScopeExpression::ScopeExpression() {}

blitz::ast::ScopeExpression::~ScopeExpression() {}

void blitz::ast::ScopeExpression::AddExpression(std::unique_ptr<expression> ex) {
	m_expressions.push_back(std::move(ex));
}

blitz::ast::FunctionExpression::FunctionExpression(ValueType returnType,
	std::string& m_name,
	std::list<std::unique_ptr<VariableExpression>> parameters, 
	std::unique_ptr<ScopeExpression> scope)
	: m_returnType(returnType), m_name(m_name), m_parameters(std::move(parameters)), m_content(std::move(scope)) {

}

blitz::ast::FunctionExpression::~FunctionExpression() {}

blitz::ast::CallExpression::CallExpression(std::string& name, std::list<std::unique_ptr<VariableExpression>> arguments)
	: m_name(name), m_arguments(std::move(arguments)) {

}

blitz::ast::CallExpression::~CallExpression() {}
