/// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "value.hpp"

blitz::ast::VariableExpression::VariableExpression(std::string& name, ValueType type /*= ValueType::Number*/)
	: m_name(name), m_type(type) {}

blitz::ast::VariableExpression::~VariableExpression() {}

blitz::ast::ValueType blitz::ast::VariableExpression::GetType() {
	return m_type;
}

blitz::ast::NumberExpression::NumberExpression(int32_t value) : value(value) {}

blitz::ast::NumberExpression::~NumberExpression() {}

blitz::ast::ValueType blitz::ast::NumberExpression::GetType() {
	return ValueType::INTEGER;
}

blitz::ast::DecimalExpression::DecimalExpression(float_t value) : value(value) {}

blitz::ast::DecimalExpression::~DecimalExpression() {}

blitz::ast::ValueType blitz::ast::DecimalExpression::GetType() {
	return ValueType::REAL;
}

blitz::ast::StringExpression::StringExpression(std::string value) : value(value) {}

blitz::ast::StringExpression::~StringExpression() {}

blitz::ast::ValueType blitz::ast::StringExpression::GetType() {
	return ValueType::STRING;
}

blitz::ast::ConstExpression::ConstExpression(std::string& name, std::unique_ptr<ValueExpression> value)
	: m_name(name), m_value(std::move(value)) {}

blitz::ast::ConstExpression::~ConstExpression() {}

blitz::ast::ValueType blitz::ast::ConstExpression::GetType() {
	return m_value->GetType();
}
